import type { AreaConfig } from '../types/game';
import { CalculationPresets } from '../utils/mathLogic';

/**
 * エリアとステージの設定データ
 * 新しいエリアやステージを追加する場合は、このファイルを編集してください
 */
export const areas: AreaConfig[] = [
  {
    id: 'area1',
    name: 'はじまりの草原',
    description: '小学1年前期（10までの計算）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 1,
        name: 'ステージ1-1：5までの足し算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 450,
        totalTime: 15000,
        calculationSettings: CalculationPresets.additionUpTo5,
        damageOnMiss: 10,
      },
      {
        id: 2,
        name: 'ステージ1-2：10までの足し算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 750,
        totalTime: 12000,
        calculationSettings: CalculationPresets.additionUpTo10,
        damageOnMiss: 10,
      },
      {
        id: 3,
        name: 'ステージ1-3：10までの引き算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 750,
        totalTime: 12000,
        calculationSettings: CalculationPresets.subtractionUpTo10,
        damageOnMiss: 10,
      },
      {
        id: 4,
        name: 'ステージ1-4：10までの加減混合',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 900,
        totalTime: 10000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo10,
        damageOnMiss: 15,
      },
      {
        id: 5,
        name: 'ボスステージ：10までの加減（スピード勝負）',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1200,
        totalTime: 8000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo10WithCarry,
        damageOnMiss: 20,
      },
    ],
  },
  {
    id: 'area2',
    name: 'しんぴの森',
    description: '小学1年後期（20までの計算・繰り上がり/下がり）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 6,
        name: 'ステージ2-1：繰り上がりあり足し算',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 12000,
        calculationSettings: CalculationPresets.additionWithCarryUpTo20,
        damageOnMiss: 15,
      },
      {
        id: 7,
        name: 'ステージ2-2：繰り下がりあり引き算',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 12000,
        calculationSettings: CalculationPresets.subtractionWithBorrowUpTo20,
        damageOnMiss: 15,
      },
      {
        id: 8,
        name: 'ステージ2-3：20までの3つの数',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1200,
        totalTime: 15000,
        calculationSettings: CalculationPresets.threeNumbersUpTo20,
        damageOnMiss: 20,
      },
      {
        id: 9,
        name: 'ステージ2-4：20までの加減混合',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 10000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo20,
        damageOnMiss: 20,
      },
      {
        id: 10,
        name: 'ボスステージ：20までの加減（ハイペース）',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1600,
        totalTime: 7000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo20,
        damageOnMiss: 30,
      },
    ],
  },
  {
    id: 'area3',
    name: 'まなつの砂丘',
    description: '小学2年前期（2桁の筆算基礎）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 11,
        name: 'ステージ3-1：2桁 ± 1桁（繰り上がりなし）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1200,
        totalTime: 10000,
        calculationSettings: CalculationPresets.twoDigitOneDigitNoCarry,
        damageOnMiss: 20,
      },
      {
        id: 12,
        name: 'ステージ3-2：2桁 ± 1桁（繰り上がりあり）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1500,
        totalTime: 12000,
        calculationSettings: CalculationPresets.twoDigitOneDigitWithCarry,
        damageOnMiss: 20,
      },
      {
        id: 13,
        name: 'ステージ3-3：2桁 ± 2桁（繰り上がりなし）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1500,
        totalTime: 15000,
        calculationSettings: CalculationPresets.twoDigitTwoDigitNoCarry,
        damageOnMiss: 25,
      },
      {
        id: 14,
        name: 'ステージ3-4：2桁 ± 2桁（繰り上がりあり）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1800,
        totalTime: 18000,
        calculationSettings: CalculationPresets.twoDigitTwoDigitWithCarry,
        damageOnMiss: 25,
      },
      {
        id: 15,
        name: 'ボスステージ：2桁加減（スピード混合）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 2200,
        totalTime: 12000,
        calculationSettings: CalculationPresets.twoDigitMixedSpeed,
        damageOnMiss: 40,
      },
    ],
  },
  {
    id: 'area4',
    name: 'めぐみの湖',
    description: '九九（エリア全10ステージ）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 16,
        name: 'ステージ4-1：一の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 8000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 1,
        },
        damageOnMiss: 20,
      },
      {
        id: 17,
        name: 'ステージ4-2：二の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 6000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 2,
        },
        damageOnMiss: 20,
      },
      {
        id: 18,
        name: 'ステージ4-3：三の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 6000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 3,
        },
        damageOnMiss: 20,
      },
      {
        id: 19,
        name: 'ステージ4-4：四の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 6000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 4,
        },
        damageOnMiss: 25,
      },
      {
        id: 20,
        name: 'ステージ4-5：五の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 5,
        },
        damageOnMiss: 25,
      },
      {
        id: 21,
        name: 'ステージ4-6：六の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 7000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 6,
        },
        damageOnMiss: 30,
      },
      {
        id: 22,
        name: 'ステージ4-7：七の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 8000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 7,
        },
        damageOnMiss: 30,
      },
      {
        id: 23,
        name: 'ステージ4-8：八の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 8000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 8,
        },
        damageOnMiss: 30,
      },
      {
        id: 24,
        name: 'ステージ4-9：九の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 8000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 9,
        },
        damageOnMiss: 30,
      },
      {
        id: 25,
        name: 'スボスステージ：全段ランダム',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 2500,
        totalTime: 5000,
        calculationSettings: CalculationPresets.multiplicationTable,
        damageOnMiss: 40,
      },
    ],
  },
];

/**
 * ステージIDからステージ設定を取得するヘルパー関数
 */
export function getStageById(stageId: number): import('../types/game').StageConfig | undefined {
  for (const area of areas) {
    const stage = area.stages.find(s => s.id === stageId);
    if (stage) return stage;
  }
  return undefined;
}

/**
 * エリアIDからエリア設定を取得するヘルパー関数
 */
export function getAreaById(areaId: string): AreaConfig | undefined {
  return areas.find(a => a.id === areaId);
}
