import type { AreaConfig } from '../types/game';
import { CalculationPresets } from '../utils/mathLogic';

/**
 * エリアとステージの設定データ
 * 新しいエリアやステージを追加する場合は、このファイルを編集してください
 */
export const areas: AreaConfig[] = [
  {
    id: 'area1',
    name: 'たしざんの はじまり（1桁）',
    description: '5までのたしざんからスタート',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 1,
        name: 'ステージ1-1：5までの足し算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 600,
        totalTime: 10000,
        calculationSettings: CalculationPresets.additionUpTo5,
        damageOnMiss: 10,
      },
      {
        id: 2,
        name: 'ステージ1-2：10までの足し算（繰なし）',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 750,
        totalTime: 8000,
        calculationSettings: CalculationPresets.additionUpTo10,
        damageOnMiss: 10,
      },
      {
        id: 3,
        name: 'ステージ1-3：10になる足し算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 900,
        totalTime: 6000,
        calculationSettings: CalculationPresets.additionUpTo10,
        damageOnMiss: 10,
      },
      {
        id: 4,
        name: 'ステージ1-4：3つの数の足し算',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 12000,
        calculationSettings: CalculationPresets.threeNumbersUpTo20,
        damageOnMiss: 15,
      },
      {
        id: 5,
        name: 'ステージ1-5(B)：10までの足し算（スピード）',
        backgroundImage: '/images/草原.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1200,
        totalTime: 5000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo10WithCarry,
        damageOnMiss: 20,
      },
    ],
  },
  {
    id: 'area2',
    name: 'ひきざんの はじまり（1桁）',
    description: '5からのひきざん、10からのひきざん',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 6,
        name: 'ステージ2-1：5からのひきざん',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 600,
        totalTime: 10000,
        calculationSettings: CalculationPresets.subtractionUpTo10,
        damageOnMiss: 15,
      },
      {
        id: 7,
        name: 'ステージ2-2：10以内のひきざん（繰なし）',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 750,
        totalTime: 8000,
        calculationSettings: CalculationPresets.subtractionWithBorrowUpTo20,
        damageOnMiss: 15,
      },
      {
        id: 8,
        name: 'ステージ2-3：10から引く計算',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 900,
        totalTime: 6000,
        calculationSettings: CalculationPresets.subtractionUpTo10,
        damageOnMiss: 20,
      },
      {
        id: 9,
        name: 'ステージ2-4：10以内の加減混合',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 10000,
        calculationSettings: CalculationPresets.additionSubtractionUpTo10,
        damageOnMiss: 20,
      },
      {
        id: 10,
        name: 'ステージ2-5(B)：10以内のひきざん（スピード）',
        backgroundImage: '/images/森林.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1200,
        totalTime: 5000,
        calculationSettings: CalculationPresets.subtractionUpTo10,
        damageOnMiss: 30,
      },
    ],
  },
  {
    id: 'area3',
    name: '2桁の たしざん',
    description: '筆算・右から入力（スモールステップ）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 11,
        name: 'ステージ3-1：2桁+1桁（繰なし）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 15000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitOneDigitNoCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          minAnswer: 10,
          maxAnswer: 99,
          mustCarry: false,
        },
        damageOnMiss: 20,
      },
      {
        id: 12,
        name: 'ステージ3-2：2桁+1桁（必ず繰上がり）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1100,
        totalTime: 15000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitOneDigitWithCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          minAnswer: 20,
          maxAnswer: 99,
          mustCarry: true,
        },
        damageOnMiss: 20,
      },
      {
        id: 13,
        name: 'ステージ3-3：2桁+2桁（繰なし・低数値）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1300,
        totalTime: 18000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitNoCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 20,
          maxAnswer: 50,
          mustCarry: false,
        },
        damageOnMiss: 25,
      },
      {
        id: 14,
        name: 'ステージ3-4：2桁+2桁（繰なし・高数値）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1500,
        totalTime: 18000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitNoCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 50,
          maxAnswer: 99,
          mustCarry: false,
        },
        damageOnMiss: 25,
      },
      {
        id: 15,
        name: 'ステージ3-5：2桁+2桁（1の位のみ繰上がり）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1700,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 30,
          maxAnswer: 80,
          mustCarry: true,
        },
        damageOnMiss: 30,
      },
      {
        id: 16,
        name: 'ステージ3-6：2桁+2桁（繰上がりあり・高数値）',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1900,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 80,
          maxAnswer: 100,
          mustCarry: true,
        },
        damageOnMiss: 35,
      },
      {
        id: 17,
        name: 'ステージ3-7(B)：足し算マスター',
        backgroundImage: '/images/砂漠.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 2200,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['+'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 10,
          maxAnswer: 100,
        },
        damageOnMiss: 40,
      },
    ],
  },
  {
    id: 'area4',
    name: '2桁の ひきざん',
    description: '筆算・右から入力（スモールステップ）',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 18,
        name: 'ステージ4-1：2桁-1桁（繰下がりなし）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1000,
        totalTime: 15000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitOneDigitNoCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          minAnswer: 10,
          maxAnswer: 90,
          mustCarry: false,
        },
        damageOnMiss: 20,
      },
      {
        id: 19,
        name: 'ステージ4-2：2桁-1桁（必ず繰下がり）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1100,
        totalTime: 15000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitOneDigitWithCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          minAnswer: 5,
          maxAnswer: 80,
          mustCarry: true,
        },
        damageOnMiss: 20,
      },
      {
        id: 20,
        name: 'ステージ4-3：2桁-2桁（繰下がりなし・低数値）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1300,
        totalTime: 18000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitNoCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 1,
          maxAnswer: 30,
          mustCarry: false,
        },
        damageOnMiss: 20,
      },
      {
        id: 21,
        name: 'ステージ4-4：2桁-2桁（繰下がりなし・高数値）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1500,
        totalTime: 18000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitNoCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 30,
          maxAnswer: 70,
          mustCarry: false,
        },
        damageOnMiss: 25,
      },
      {
        id: 22,
        name: 'ステージ4-5：2桁-2桁（10の位から借りる）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1700,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 10,
          maxAnswer: 50,
          mustCarry: true,
        },
        damageOnMiss: 30,
      },
      {
        id: 23,
        name: 'ステージ4-6：2桁-2桁（繰下がりあり・高数値）',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1900,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 1,
          maxAnswer: 80,
          mustCarry: true,
        },
        damageOnMiss: 35,
      },
      {
        id: 24,
        name: 'ステージ4-7(B)：引き算マスター',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 2200,
        totalTime: 20000,
        displayMode: 'vertical',
        calculationSettings: {
          ...CalculationPresets.twoDigitTwoDigitWithCarry,
          allowedOperators: ['-'],
          operand1Min: 10,
          operand2Min: 10,
          minAnswer: 1,
          maxAnswer: 90,
        },
        damageOnMiss: 40,
      },
    ],
  },
  {
    id: 'area5',
    name: '九九チャレンジ',
    description: '一の段〜九の段＋全段ランダムボス',
    image: '/images/世界地図.png',
    stages: [
      {
        id: 25,
        name: 'ステージ5-1：一の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 1,
          minAnswer: 1,
          maxAnswer: 9,
        },
        damageOnMiss: 20,
      },
      {
        id: 26,
        name: 'ステージ5-2：二の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 2,
          minAnswer: 2,
          maxAnswer: 18,
        },
        damageOnMiss: 20,
      },
      {
        id: 27,
        name: 'ステージ5-3：三の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 3,
          minAnswer: 3,
          maxAnswer: 27,
        },
        damageOnMiss: 20,
      },
      {
        id: 28,
        name: 'ステージ5-4：四の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 4,
          minAnswer: 4,
          maxAnswer: 36,
        },
        damageOnMiss: 25,
      },
      {
        id: 29,
        name: 'ステージ5-5：五の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 5,
          minAnswer: 5,
          maxAnswer: 45,
        },
        damageOnMiss: 25,
      },
      {
        id: 30,
        name: 'ステージ5-6：六の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 6,
          minAnswer: 6,
          maxAnswer: 54,
        },
        damageOnMiss: 30,
      },
      {
        id: 31,
        name: 'ステージ5-7：七の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 7,
          minAnswer: 7,
          maxAnswer: 63,
        },
        damageOnMiss: 30,
      },
      {
        id: 32,
        name: 'ステージ5-8：八の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 8,
          minAnswer: 8,
          maxAnswer: 72,
        },
        damageOnMiss: 30,
      },
      {
        id: 33,
        name: 'ステージ5-9：九の段',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 1350,
        totalTime: 5000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          multiplicationTableRow: 9,
          minAnswer: 9,
          maxAnswer: 81,
        },
        damageOnMiss: 30,
      },
      {
        id: 34,
        name: 'ステージ5-10(B)：全段ランダム',
        backgroundImage: '/images/オアシス.png',
        enemyImage: '/images/stage1-1.png',
        enemyHP: 2000,
        totalTime: 4000,
        calculationSettings: {
          digits1: 1,
          digits2: 1,
          allowedOperators: ['×'] as const,
          multiplicationTableOnly: true,
          minAnswer: 1,
          maxAnswer: 81,
        },
        damageOnMiss: 40,
      },
    ],
  },
];

/**
 * ステージIDからステージ設定を取得するヘルパー関数
 */
export function getStageById(stageId: number): import('../types/game').StageConfig | undefined {
  for (const area of areas) {
    const stage = area.stages.find(s => s.id === stageId);
    if (stage) return stage;
  }
  return undefined;
}

/**
 * エリアIDからエリア設定を取得するヘルパー関数
 */
export function getAreaById(areaId: string): AreaConfig | undefined {
  return areas.find(a => a.id === areaId);
}
